complete2short = {
	"Izi Dream": "IZI",
	"Team MCES": "MCES",
	"Team Oplon":"OPL",
	"Mirage Elyandra":"ME",
	"GameWard":"GW",
	"GamersOrigin":"GO",
	"Team GO":"GO",
	"Team BDS Academy":"BDSA",
	"Solary":"SLY",
	"Misfits Premier":"MSFP",
	"Karmine Corp":"KC",
	"Vitality.Bee":"VITB",
	"LDLC OL":"LDLC",
	"Karmine Corp Blue":"KCB",
	"Gentle Mates":"M8",
	"Team Du Sud":"TDS",
	"Astralis":"AST",
	"Team BDS":"BDS",
	"SK Gaming":"SK",
	"MAD Lions":"MAD",
	"Team Vitality":"VIT",
	"G2 Esports":"G2",
	"Excel Esports":"XL",
	"KOI (Spanish Team)":"KOI",
	"Team Heretics":"TH",
	"Fnatic":"FNC",
	"BK ROG Esports": "BKR",
	"Aegis (French Team)": "AEG",
	"Rogue (European Team)": "RGE",
	"GIANTX": "GX",
	"MAD Lions KOI": "MDK",
	}
	
	
complete2short.update({
	"Akroma": "AKR",
	"Atletec": "ATL",
	"Joblife": "JL",
	"Klanik Esport": "KE",
	"Lille Esport": "LiL",
	"MHSC Esport": "MHSC",
	"MS Company": "MS",
	"Project Conquerors": "PCS",
	"Team Du Sud": "TDS",
	"ViV Esport": "ViV",
	"Zerance": "ZER",
	"Esprit Shōnen": "ES",
	"Ici Japon Corp. Esport": "IJC",
	})
	
complete2short.update({
	"Spinebusters E-Sport":"SP",
	"TeamOrangeGaming":"TOG",
	"Kaufland Hangry Knights":"KHK",
	"ROSSMANN Centaurs":"ROSS",
	"DKB Diamonds":"DKB",
	"Direct Rising eSports":"DR",
	"EPIC-DUDES":"ED",
	"All for One Gaming":"A41G",
	"WeSports":"WES",
	"eSports Cologne GAMERS ONLY":"ECO.GO",
	})

complete2short.update({
	"KT Rolster Challengers":"KT.C",
	"Nongshim Esports Academy":"NS.EA",
	"Dplus KIA Challengers":"DK.C",
	"Hanwha Life Esports Challengers":"HLE.C",
	"Kwangdong Freecs Challengers":"KDF.C",
	"DRX Challengers":"DRX.C",
	"OKSavingsBank BRION Challengers":"BRO.C",
	"FearX Youth":"FOX.Y",
	"T1 Esports Academy":"T1.EA",
	"Gen.G Global Academy":"GEN.GA",
	})


complete2short.update({
	"KT Rolster":"KT",
	"Nongshim RedForce":"NS",
	"Dplus KIA":"DK",
	"Hanwha Life Esports":"HLE",
	"Kwangdong Freecs":"KDF",
	"DRX":"DRX",
	"OKSavingsBank BRION":"BRO",
	"FearX":"FOX",
	"T1":"T1",
	"Gen.G":"GEN",
	})